[pytest]
python_files = pytest_*.py
markers =
	generic: generic hardware test
	host_test: host-side test
	macos: macOS specific test
	qemu: qemu test
addopts =
	--embedded-services esp,idf
	--target esp32
	--reruns 2
	--reruns-delay 1
	--ignore-result-cases __DUMMY_DO_NOT_MATCH__
	--ignore-result-files .pytest-ignore-results.txt
	--ignore-no-tests-collected-error
	-m "generic and not host_test and not qemu"
